# <region>:
  # <autoscaling group name>: <desired capacity default>

us-east-1:
  maelstrom: 4
  anemoi: 4
  anemoi-backup: 0

us-west-2:
  maelstrom: 4
  anemoi: 4
  maelstrom-backup: 0
  anmeoi-backup: 0
